const product = {
    title: "Adidas",
    items: [
      {
        id: "0p0x1",
        title: "Adidas BB 2.0",
        text: "MEN Running Shoes",
        rating: "4.9",
        btn: "Buy Now",
        img: "/assets/ad1.png",
        price: "220",
        color: "from-slate-900 to-black",
        shadow: "shadow-lg shadow-black",
      },
      {
        id: "0p0x2",
        title: "Adidas Braze",
        text: "MEN Running Shoes",
        rating: "4.9",
        btn: "Buy Now",
        img: "/assets/ad2.png",
        price: "200",
        color: "from-gray-900 to-yellow-500",
        shadow: "shadow-lg shadow-yellow-500",
      },
      {
        id: "0p0x3",
        title: "Adidas Rocz",
        text: "MEN Running Shoes",
        rating: "4.9",
        btn: "Buy Now",
        img: "/assets/ad3.png",
        price: "200",
        color: "from-gray-900 to-black-500",
        shadow: "shadow-lg shadow-black-500",
      },
      {
        id: "0p0x4",
        title: "Adidas Bang",
        text: "MEN Running Shoes",
        rating: "4.9",
        btn: "Buy Now",
        img: "/assets/ad4.png",
        price: "200",
        color: "from-sky-600 to-indigo-600",
        shadow: "shadow-lg shadow-blue-500",
      },
      {
        id: "0p0x5",
        title: "Adidas Oronate",
        text: "MEN Running Shoes",
        rating: "4.9",
        btn: "Buy Now",
        img: "/assets/ad5.png",
        price: "300",
        color: "from-orange-500 to-amber-500",
        shadow: "shadow-lg shadow-orange-500",
      },
      {
        id: "0p0x6",
        title: "Adidas Bloat",
        text: "MEN Running Shoes",
        rating: "4.9",
        btn: "Buy Now",
        img: "/assets/ad8.png",
        price: "240",
        color: "from-orange-500 to-blue-500",
        shadow: "shadow-lg shadow-blue-500",
      },
      {
        id: "0p0x7",
        title: "Adidas Soat",
        text: "MEN Running Shoes",
        rating: "4.9",
        btn: "Buy Now",
        img: "/assets/ad6.png",
        price: "223",
        color: "from-slate-900 to-black",
        shadow: "shadow-lg shadow-black",
      },
      {
        id: "0p0x8",
        title: "Adidas Sports",
        text: "MEN Running Shoes",
        rating: "4.9",
        btn: "Buy Now",
        img: "/assets/ad9.png",
        price: "193",
        color: "from-yellow-500 to-yellow-500",
        shadow: "shadow-lg shadow-yellow-500",
      },
      {
        id: "0p0x9",
        title: "Adidas Signare",
        text: "MEN Running Shoes",
        rating: "4.9",
        btn: "Buy Now",
        img: "/assets/ad10.png",
        price: "333",
        color: "from-gray-900 to-yellow-500",
        shadow: "shadow-lg shadow-yellow-500",
      },
      {
        id: "0p0x10",
        title: "Adidas Spring",
        text: "MEN Running Shoes",
        rating: "4.9",
        btn: "Buy Now",
        img: "/assets/ad11.png",
        price: "203",
        color: "from-gray-900 to-lime-500",
        shadow: "shadow-lg shadow-green-500",
      },
      {
        id: "0p0x12",
        title: "Adidas Plone",
        text: "MEN Running Shoes",
        rating: "4.9",
        btn: "Buy Now",
        img: "/assets/ad12.png",
        price: "300",
        color: "from-violet-500 to-indigo-500",
        shadow: "shadow-lg shadow-violet-500",
      },
      {
        id: "0p0x13",
        title: "Adidas Eyenotic 2.0",
        text: "MEN Running Shoes",
        rating: "4.9",
        btn: "Buy Now",
        img: "/assets/ad13.png",
        price: "343",
        color: "from-green-600 to-green-300",
        shadow: "shadow-lg shadow-green-600",
      },
    ]
}
module.exports = product;