const product = {
    title: "Puma",
    items: [
      {
        id: "0p0x1",
        title: "Puma Adapt 2.O",
        text: "MEN Running Shoes",
        rating: "4.9",
        btn: "Buy Now",
        img: "/assets/pu1.png",
        price: "260",
        color: "from-blue-600 to-blue-500",
        shadow: "shadow-lg shadow-blue-500",
      },
      {
        id: "0p0x2",
        title: "Puma Bograt",
        text: "MEN Running Shoes",
        rating: "4.9",
        btn: "Buy Now",
        img: "/assets/pu2.png",
        price: "200",
        color: "from-slate-900 to-black",
        shadow: "shadow-lg shadow-black",
      },
      {
        id: "0p0x3",
        title: "Puma Cagrac Lite",
        text: "MEN Running Shoes",
        rating: "4.9",
        btn: "Buy Now",
        img: "/assets/pu3.png",
        price: "300",
        color: "from-red-500 to-rose-500",
        shadow: "shadow-lg shadow-rose-500",
      },
      {
        id: "0p0x3",
        title: "Puma Magnite 2",
        text: "MEN Running Shoes",
        rating: "4.9",
        btn: "Buy Now",
        img: "/assets/pu4.png",
        price: "200",
        color: "from-slate-900 to-black",
        shadow: "shadow-lg shadow-black",
      },
      {
        id: "0p0x5",
        title: "Puma Bograt",
        text: "MEN Running Shoes",
        rating: "4.9",
        btn: "Buy Now",
        img: "/assets/pu5.png",
        price: "200",
        color: "from-orange-500 to-amber-500",
        shadow: "shadow-lg shadow-orange-500",
      },
      {
        id: "0p0x6",
        title: "Puma Chromite",
        text: "MEN Running Shoes",
        rating: "4.9",
        btn: "Buy Now",
        img: "/assets/pu6.png",
        price: "210",
        color: "from-red-500 to-rose-500",
        shadow: "shadow-lg shadow-rose-500",
      },
      {
        id: "0p0x7",
        title: "Puma Luminite 2",
        text: "MEN Running Shoes",
        rating: "4.9",
        btn: "Buy Now",
        img: "/assets/pu7.png",
        price: "180",
        color: "from-sky-600 to-indigo-600",
        shadow: "shadow-lg shadow-blue-500",
      },
      {
        id: "0p0x8",
        title: "Puma Bograt",
        text: "MEN Running Shoes",
        rating: "4.9",
        btn: "Buy Now",
        img: "/assets/pu8.png",
        price: "200",
        color: "from-gray-900 to-yellow-500",
        shadow: "shadow-lg shadow-yellow-500",
      },
    ],
}
module.exports = product;